GET http://127.0.0.1:5000/customers

###
## REGISTER USER
POST http://127.0.0.1:5000/customers
Content-Type: application/json

{
    "id": "1",
    "name": "Robinson Ngecu",
    "code":"RN2"
}

###
POST http://127.0.0.1:5000/orders
Content-Type: application/json

{
    "username": "Robinson",
    "password": "3W!W.:srzc4r^!P"
}

