apiVersion: v1
kind: Service
metadata:
  name: ngnix
spec:
  type: LoadBalancer
  selector:
    app: ngnix
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: ngnix
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
